version: "3.8"

services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: flight_chatbot_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: huy123456789
      POSTGRES_DB: flight_chatbot
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: flight_chatbot_redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    restart: unless-stopped

volumes:
  pgdata:
  redisdata:
